### ISSUE TITLE
What file icons are you using in the screen shots?

### ISSUE THREAD

**Issue by lightify97** [GraphicOwls/electronic-dawn-theme#1]
What file icons are you using in the screen shots?

**Comment by GraphicOwls** [comment]
Hey,

I am using [Moxer Icons](https://marketplace.visualstudio.com/items?itemName=Equinusocio.moxer-icons) for all the file icons & [Fluent Icons](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons) for the app icons. Another icon set that I love is [Gruvbox Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=JonathanHarty.gruvbox-material-icon-theme) 🤙
